
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router-dom";




const About = lazy(() => import("./pages/About.tsx"));
const App = lazy(() => import("./pages/App.tsx"));
const Blog = lazy(() => import("./pages/Blog.tsx"));
const BlogCategories = lazy(() => import("./pages/BlogCategories.tsx"));
const Blogs = lazy(() => import("./pages/Blogs.tsx"));
const CarDetailingPricing = lazy(() => import("./pages/CarDetailingPricing.tsx"));
const Contact = lazy(() => import("./pages/Contact.tsx"));
const Home1 = lazy(() => import("./pages/Home1.tsx"));
const Home2 = lazy(() => import("./pages/Home2.tsx"));
const HowLocalServWorks = lazy(() => import("./pages/HowLocalServWorks.tsx"));
const Industries = lazy(() => import("./pages/Industries.tsx"));
const NewPost = lazy(() => import("./pages/NewPost.tsx"));
const PrivacyPolicy = lazy(() => import("./pages/PrivacyPolicy.tsx"));
const ProfessionalAutoDetailingVsDiyLa = lazy(() => import("./pages/ProfessionalAutoDetailingVsDiyLa.tsx"));
const TermsConditions = lazy(() => import("./pages/TermsConditions.tsx"));
const WhatIsLocalServ = lazy(() => import("./pages/WhatIsLocalServ.tsx"));
const WhyAiIsTheFutureOfLocalServices = lazy(() => import("./pages/WhyAiIsTheFutureOfLocalServices.tsx"));

export const userRoutes: RouteObject[] = [



	{ path: "/about", element: <About />},
	{ path: "/", element: <App />},
	{ path: "/blog", element: <Blog />},
	{ path: "/blog-categories", element: <BlogCategories />},
	{ path: "/blogcategories", element: <BlogCategories />},
	{ path: "/blogs", element: <Blogs />},
	{ path: "/car-detailing-pricing", element: <CarDetailingPricing />},
	{ path: "/cardetailingpricing", element: <CarDetailingPricing />},
	{ path: "/contact", element: <Contact />},
	{ path: "/home1", element: <Home1 />},
	{ path: "/home2", element: <Home2 />},
	{ path: "/how-local-serv-works", element: <HowLocalServWorks />},
	{ path: "/howlocalservworks", element: <HowLocalServWorks />},
	{ path: "/industries", element: <Industries />},
	{ path: "/new-post", element: <NewPost />},
	{ path: "/newpost", element: <NewPost />},
	{ path: "/privacy-policy", element: <PrivacyPolicy />},
	{ path: "/privacypolicy", element: <PrivacyPolicy />},
	{ path: "/professional-auto-detailing-vs-diy-la", element: <ProfessionalAutoDetailingVsDiyLa />},
	{ path: "/professionalautodetailingvsdiyla", element: <ProfessionalAutoDetailingVsDiyLa />},
	{ path: "/terms-conditions", element: <TermsConditions />},
	{ path: "/termsconditions", element: <TermsConditions />},
	{ path: "/what-is-local-serv", element: <WhatIsLocalServ />},
	{ path: "/whatislocalserv", element: <WhatIsLocalServ />},
	{ path: "/why-ai-is-the-future-of-local-services", element: <WhyAiIsTheFutureOfLocalServices />},
	{ path: "/whyaiisthefutureoflocalservices", element: <WhyAiIsTheFutureOfLocalServices />},

];
